version: '3'

services:
  steamauto:
    build:
      context: ./Steamauto
      dockerfile: ../Dockerfile
    container_name: steamauto
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./session:/app/session
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai